version: "3"

services:
  api_gateway:
    container_name: api_gateway
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./nginx/log:/var/log/nginx:z
    ports:
      - "8080:80"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z

  nginx_exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter
    depends_on:
      - api_gateway
    environment:
      - SCRAPE_URI=http://api_gateway/stub_status

  nginx_log_exporter:
    container_name: nginx_log_exporter
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    depends_on:
      - api_gateway
    volumes:
      - ./nginx/log:/var/log/nginx:z
      - ./nginx/log_exporter_config.hcl:/etc/prometheus-nginxlog-exporter.hcl:z
    command:
      - -config-file
      - /etc/prometheus-nginxlog-exporter.hcl

  grafana:
    container_name: grafana
    image: grafana/grafana
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana:z

networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16
volumes:
  prometheus_data:
  grafana_data:
