global:
  scrape_interval: 15s
  external_labels:
    monitor: "docker-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nginx"
    scrape_interval: 5s
    static_configs:
      - targets: ["nginx_exporter:9113", "nginx_log_exporter:4040"]